spring.application.name=discografia
docker run -p 443:443 -e spring.data.mongodb.uri=mongodb+srv://jessicacruzat_db_user:tON5znQIjXVLk7H4@eva-u2-spring.twsuof9.mongodb.net/discografica-db?retryWrites=true&w=majority&appName=eva-u2-spring
spring.data.mongodb.database=discografica-db